# keras 安裝

conda install -c conda-forge keras

# theano 安裝

conda install -c conda-forge theano

# tensorflow 安裝

conda install -c conda-forge tensorflow

### theano , tensorlfow 擇一安裝

## 將keras backend 改為 tensorflow

https://github.com/keras-team/keras/issues/6925

In [1]:
from __future__ import print_function
import keras
from keras.datasets import mnist
from keras.models import Sequential,Model
from keras.layers import Dense, Dropout, Flatten,Activation
from keras.layers import Conv2D, MaxPooling2D,Input,BatchNormalization
import matplotlib.pylab as plt
import numpy as np
from keras.layers import Convolution2D

C:\Users\adm\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


# Dense example

In [2]:
from keras import backend as K
_input = Input(shape=(3,))
_output = Dense(2)(_input)
model = Model(inputs=_input, outputs=_output)

test_input = np.random.random((1,3))
test_output = model.predict(test_input)
print ('test_input.shape',test_input.shape)
print (test_input)
print ('test_output.shape',test_output.shape)
print (test_output)

test_input.shape (1, 3)
[[0.142218   0.93216578 0.85670315]]
test_output.shape (1, 2)
[[ 0.24651913 -0.9596418 ]]


In [3]:
w = model.get_weights()
print ('weights shape',w[0].shape)
print (w[0])
print ('bias shape',w[1].shape)
print (w[1])

weights shape (3, 2)
[[ 0.3564055   0.07868588]
 [-0.02549016 -0.54719895]
 [ 0.25632322 -0.53782016]]
bias shape (2,)
[0. 0.]


# activation example

In [4]:
_input = Input(shape=(5,))
_output = Activation('relu')(_input) #輸入小於0 輸出為0
#_output = Activation('softmax')(_input) #輸出為0~1
#_output = Activation('sigmoid')(_input) #輸出中最大值接近1 其他輸出趨近於0
#_output = Activation('tanh')(_input) #輸出為-1~1
model = Model(inputs=_input, outputs=_output)
test_input = np.random.random((1,5)) * 20 - 10
test_output = model.predict(test_input)

print ('test_input',test_input.shape)
print (test_input)
print ('test_output',test_output.shape)
print (test_output)

test_input (1, 5)
[[ 6.23906458 -6.71709116  4.2575992  -0.40897475  0.45344982]]
test_output (1, 5)
[[6.2390647  0.         4.2575994  0.         0.45344982]]


# Conv2d example

In [5]:
_input = Input(shape=(3,3,2))
_output = Conv2D(4, kernel_size=(3, 3))(_input)
model = Model(inputs=_input, outputs=_output)

test_input = np.random.random((1,3,3,2))
test_output = model.predict(test_input)
print (test_input.shape)
print (test_input)
print (test_output.shape)
print (test_output)

(1, 3, 3, 2)
[[[[0.47184671 0.50985619]
   [0.88865374 0.3343746 ]
   [0.32016907 0.39706613]]

  [[0.74792539 0.02621117]
   [0.41634754 0.29575214]
   [0.45113064 0.69726718]]

  [[0.05697901 0.46491351]
   [0.07723063 0.48251197]
   [0.05064448 0.08468584]]]]
(1, 1, 1, 4)
[[[[ 0.5248277   0.41947055 -0.21354976  0.4699921 ]]]]


In [6]:
w = model.get_weights()
print ('weights shape',w[0].shape)
print (w[0])
print ('bias shape',w[1].shape)
print (w[1])

weights shape (3, 3, 2, 4)
[[[[-0.3186316   0.05324498 -0.16964722  0.12221026]
   [-0.00514713  0.21883312  0.1697717  -0.03339085]]

  [[ 0.31823555  0.2610902  -0.25007161  0.04769301]
   [ 0.27161083 -0.00252733 -0.02658334  0.07360864]]

  [[ 0.11606845  0.20697102  0.07600412  0.31245282]
   [-0.27881163  0.301855    0.01319185  0.07290277]]]


 [[[ 0.18864062 -0.13308558  0.00150624  0.03184447]
   [ 0.29555258 -0.01624456 -0.14593546  0.26951924]]

  [[ 0.07240662 -0.2427756   0.10617876  0.004639  ]
   [ 0.29312238 -0.067444   -0.16948494  0.2137337 ]]

  [[ 0.09433365 -0.2666852  -0.11172709  0.19384375]
   [ 0.0436376   0.22101316  0.11255917  0.03866681]]]


 [[[ 0.06108975  0.24287501  0.1384503  -0.02227163]
   [-0.13203907  0.3003539  -0.07826987  0.14851704]]

  [[ 0.275754    0.08978114 -0.16495237 -0.07027578]
   [ 0.2402443  -0.24283442  0.03883281 -0.12829137]]

  [[-0.25602698 -0.3155958  -0.15358281  0.04103407]
   [-0.3221473   0.30010393 -0.09093675  0.24100044]

# Flatten example (CNN to MLP)

In [7]:
_input = Input(shape=(3,3,2))
_output = Flatten()(_input)
model = Model(inputs=_input, outputs=_output)
test_input = np.random.random((1,3,3,2))
test_output = model.predict_on_batch(test_input)

print ('test_input',test_input.shape)
print (test_input)
print ('test_output',test_output.shape)
print (test_output)

test_input (1, 3, 3, 2)
[[[[0.44488774 0.97715578]
   [0.23437948 0.09571922]
   [0.06036802 0.82900185]]

  [[0.08138948 0.46415936]
   [0.86632128 0.16868592]
   [0.08037857 0.14869628]]

  [[0.64424894 0.57973077]
   [0.04033299 0.14412855]
   [0.17744161 0.78047032]]]]
test_output (1, 18)
[[0.44488773 0.9771558  0.23437949 0.09571922 0.06036802 0.82900184
  0.08138948 0.46415937 0.86632127 0.16868591 0.08037858 0.14869627
  0.64424896 0.57973075 0.04033299 0.14412856 0.17744161 0.7804703 ]]
